from flask import Flask, request, jsonify
import uuid
from groq import Groq
from dotenv import load_dotenv
import os
import re
import json
import sqlite3
from datetime import datetime, timezone
import math


load_dotenv()

app = Flask(__name__)
@app.route('/')
def home():
    return "Provenance Guard is running!"

DB_PATH = "audit_log.db"
def init_db():
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS audit_log (
                content_id  TEXT,
                creator_id  TEXT,
                timestamp   TEXT,
                attribution TEXT,
                confidence  REAL,
                status      TEXT,
                llm_score     REAL,
                llm_rationale TEXT,
                stylometric_score   REAL,
                text_excerpt  TEXT

            )
        """)
init_db()
def log_event(entry):
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute(
            "INSERT INTO audit_log VALUES (:content_id, :creator_id, :timestamp, "
            ":attribution, :confidence, :status, :llm_score, :llm_rationale, :text_excerpt)",
            {**entry, "timestamp": datetime.now(timezone.utc).isoformat()},
        )




def read_log(limit=20):
    with sqlite3.connect(DB_PATH) as conn:
        conn.row_factory = sqlite3.Row
        rows = conn.execute(
            "SELECT * FROM audit_log ORDER BY timestamp DESC LIMIT ?", (limit,)
        ).fetchall()
    return [dict(row) for row in rows]


#groq classifier
def llm_classify(text: str) -> dict:
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        return {"score": 0.5, "rationale": "API key not found in environment variables."}
    client = Groq(api_key=api_key)
    prompt = f"""Your purpose is to distinguish between human-written and AI-generated text. Analyze the following text and assess the probability that it was generated by an AI model as opposed to it being written by a human. 
    Consider the following factors in your assessment:
    - Uniformity of tone and sentence structure
    - Presence or absence of genuine personal voice, idiosyncrasies, or lived experience
    - Hedging language patterns typical of LLMs ("it is important to note", "it is worth mentioning", "furthermore")
    - Vocabulary diversity and naturalness
    - Emotional authenticity vs. emotional flatness
    - Whether the writing feels genuinely spontaneous or constructed
    Respond ONLY with a JSON object in this exact format (no other text):
    {{"score": <float between 0.0 and 1.0>, "rationale": "<one to two sentences explaining your reasoning>"}}
    where score = 0.0 means definitely human-written, and score = 1.0 means definitely AI-generated.
    Text to analyze: {text}
"""
    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=200,
            temperature=0.1,
        )
        raw = response.choices[0].message.content.strip()
        raw = re.sub(r"```(?:json)?", "", raw).strip().rstrip("```").strip()
        result = json.loads(raw)
        score = float(result.get("score", 0.5))
        score = max(0.0, min(1.0, score))
        return {"score": score, "rationale": result.get("rationale", "")}
    except Exception as e:
        return {"score": 0.5, "rationale": f"Error during classification: {str(e)}"}

def stylometric_classify(text: str) -> float:
    """
    Computes three structural metrics and combines them into a single
    AI-probability score (1.0 = very likely AI-generated).
 
    Metrics:
      1. Sentence length variance  — low variance → AI
      2. Type-token ratio (TTR)    — low vocabulary diversity → AI
      3. Expressive punctuation    — low density → AI
    """
    sentences = [s.strip() for s in re.split(r"[.!?]+", text) if s.strip()]
    if len(sentences) < 2:
        # Too short for reliable structural analysis — return neutral
        return 0.5
 
    # ── Metric 1: Sentence length variance ──
    word_counts = [len(s.split()) for s in sentences]
    mean_wc = sum(word_counts) / len(word_counts)
    variance = sum((x - mean_wc) ** 2 for x in word_counts) / len(word_counts)
    std_dev = math.sqrt(variance)
    # std_dev > 15 → very human; std_dev < 2 → very AI
    # Map [0, 15] → [1.0, 0.0]
    variance_score = max(0.0, min(1.0, 1.0 - (std_dev / 15.0)))
 
    # ── Metric 2: Type-token ratio ──
    words = re.findall(r"\b[a-zA-Z]+\b", text.lower())
    if not words:
        ttr_score = 0.5
    else:
        ttr = len(set(words)) / len(words)
        # TTR < 0.4 → AI-like; TTR > 0.8 → human-like
        # Map [0.4, 0.8] → [1.0, 0.0]
        ttr_score = max(0.0, min(1.0, 1.0 - (ttr - 0.4) / 0.4))
 
    # ── Metric 3: Expressive punctuation density ──
    expressive_punct = len(re.findall(r"[—–…!?;()\[\]]", text))
    punct_density = expressive_punct / max(1, len(words))
    # > 0.08 → human-like; < 0.01 → AI-like
    # Map [0, 0.08] → [1.0, 0.0]
    punct_score = max(0.0, min(1.0, 1.0 - (punct_density / 0.08)))
 
    return round(0.4 * variance_score + 0.4 * ttr_score + 0.2 * punct_score, 4)
 
 
# ── Confidence Scoring ────────────────────────────────────────────────────────
 
def compute_confidence(llm_score: float, stylometric_score: float) -> dict:
    """
    Combines both signals into a final confidence score and attribution verdict.
 
    Weighting: LLM 60%, stylometric 40%
    Thresholds (asymmetric — favours false-negative over false-positive):
      >= 0.70  → likely_ai
      0.40–0.69 → uncertain
      < 0.40   → likely_human
    """
    confidence = round(0.6 * llm_score + 0.4 * stylometric_score, 4)
 
    if confidence >= 0.70:
        attribution = "likely_ai"
    elif confidence >= 0.40:
        attribution = "uncertain"
    else:
        attribution = "likely_human"
 
    return {"confidence": confidence, "attribution": attribution}


def placeholder_label(attribution: str, confidence: float) -> str:
    pct = round(confidence * 100)
    return {
        "likely_ai":    f"Likely AI-generated (confidence: {pct}%)",
        "uncertain":    f"Authorship uncertain (confidence: {pct}%)",
        "likely_human": f"Likely human-written (confidence: {pct}%)",
    }[attribution]




@app.route("/submit", methods=["POST"])
def submit():
    data=request.get_json(silent=True)
    if not data:
        return jsonify({"error": "Invalid JSON data"}), 400
    text=data.get("text", "").strip()
    creator_id=data.get("creator_id", "").strip()
    if not text:
        return jsonify({"error": "Missing 'text' field"}), 400
    if not creator_id:
        return jsonify({"error": "Missing 'creator_id' field"}), 400
    if len(text) < 10:
        return jsonify({"error": "Text is too short to analyze, must be at least 10 characters"}), 400


    llm_result = llm_classify(text)
    stylo_score= stylometric_classify(text)
    scoring = compute_confidence(llm_result["score"], stylo_score)
    label = placeholder_label(scoring["attribution"], scoring["confidence"])
    content_id = str(uuid.uuid4())

    log_event({
        "content_id": content_id,
        "creator_id": creator_id,
        "attribution": scoring["attribution"],
        "confidence": scoring["confidence"],
        "status": "classified",
        "llm_score": llm_result["score"],
        "llm_rationale": llm_result["rationale"],
        "stylometric_score": stylo_score,
        "text_excerpt": text[:200]
    })
    return jsonify({
        "content_id": content_id,
        "attribution": scoring["attribution"],
        "confidence": scoring["confidence"],
        "label": label,
        "llm_score": llm_result["score"],
        "llm_rationale": llm_result["rationale"],
        "stylometric_score": stylo_score,
        "text_excerpt": text[:200]
    }), 200
 
@app.route("/log", methods=["GET"])
def view_log():
    return jsonify({"entries": read_log()}), 200

#this has to be the last thing
if __name__ == '__main__':
    app.run(port=5000, debug=True)
