from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
import uuid
from groq import Groq
from dotenv import load_dotenv
import os
import re
import json
import sqlite3
from datetime import datetime, timezone
import math


load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)


@app.route('/')
def home():
    return "Provenance Guard is running!"

DB_PATH = "audit_log.db"
def init_db():
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS audit_log (
                content_id  TEXT,
                creator_id  TEXT,
                timestamp   TEXT,
                attribution TEXT,
                confidence  REAL,
                status      TEXT,
                llm_score     REAL,
                llm_rationale TEXT,
                stylometric_score   REAL,
                text_excerpt  TEXT,
                appeal_timestamp    TEXT,
                appeal_reasoning    TEXT

            )
        """)
init_db()
def log_event(entry):
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute(
            "INSERT INTO audit_log VALUES (:content_id, :creator_id, :timestamp, "
            ":attribution, :confidence, :status, :llm_score, :llm_rationale, :stylometric_score, :text_excerpt, :appeal_timestamp, :appeal_reasoning)",
            {
                "appeal_timestamp": None,
                "appeal_reasoning": None,
                **entry,
                "timestamp": datetime.now(timezone.utc).isoformat()
                },
        )




def read_log(limit=20):
    with sqlite3.connect(DB_PATH) as conn:
        conn.row_factory = sqlite3.Row
        rows = conn.execute(
            "SELECT * FROM audit_log ORDER BY timestamp DESC LIMIT ?", (limit,)
        ).fetchall()
    return [dict(row) for row in rows]


def get_record(content_id: str):
    with sqlite3.connect(DB_PATH) as conn:
        conn.row_factory = sqlite3.Row
        row = conn.execute(
            "SELECT * FROM audit_log WHERE content_id = ?", (content_id,)
        ).fetchone()
    return dict(row) if row else None
 
def update_appeal(content_id: str, reasoning: str, timestamp: str):
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute(
            "UPDATE audit_log SET status = 'under_review', "
            "appeal_timestamp = ?, appeal_reasoning = ? "
            "WHERE content_id = ?",
            (timestamp, reasoning, content_id),
        )



#groq classifier
def llm_classify(text: str) -> dict:
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        return {"score": 0.5, "rationale": "API key not found in environment variables."}
    client = Groq(api_key=api_key)
    prompt = f"""Your purpose is to distinguish between human-written and AI-generated text. Analyze the following text and assess the probability that it was generated by an AI model as opposed to it being written by a human. 
    Consider the following factors in your assessment:
    - Uniformity of tone and sentence structure
    - Presence or absence of genuine personal voice, idiosyncrasies, or lived experience
    - Hedging language patterns typical of LLMs ("it is important to note", "it is worth mentioning", "furthermore")
    - Vocabulary diversity and naturalness
    - Emotional authenticity vs. emotional flatness
    - Whether the writing feels genuinely spontaneous or constructed
    Respond ONLY with a JSON object in this exact format (no other text):
    {{"score": <float between 0.0 and 1.0>, "rationale": "<one to two sentences explaining your reasoning>"}}
    where score = 0.0 means definitely human-written, and score = 1.0 means definitely AI-generated.
    Text to analyze: {text}
"""
    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=200,
            temperature=0.1,
        )
        raw = response.choices[0].message.content.strip()
        raw = re.sub(r"```(?:json)?", "", raw).strip().rstrip("```").strip()
        result = json.loads(raw)
        score = float(result.get("score", 0.5))
        score = max(0.0, min(1.0, score))
        return {"score": score, "rationale": result.get("rationale", "")}
    except Exception as e:
        return {"score": 0.5, "rationale": f"Error during classification: {str(e)}"}

def stylometric_classify(text: str) -> float:
    """
    Computes three structural metrics and combines them into a single
    AI-probability score (1.0 = very likely AI-generated).
 
    Metrics:
      1. Sentence length variance  — low variance → AI
      2. Type-token ratio (TTR)    — low vocabulary diversity → AI
      3. Expressive punctuation    — low density → AI
    """
    sentences = [s.strip() for s in re.split(r"[.!?]+", text) if s.strip()]
    if len(sentences) < 2:
        # Too short for reliable structural analysis — return neutral
        return 0.5
 
    # ── Metric 1: Sentence length variance ──
    word_counts = [len(s.split()) for s in sentences]
    mean_wc = sum(word_counts) / len(word_counts)
    variance = sum((x - mean_wc) ** 2 for x in word_counts) / len(word_counts)
    std_dev = math.sqrt(variance)
    # std_dev > 15 → very human; std_dev < 2 → very AI
    # Map [0, 15] → [1.0, 0.0]
    variance_score = max(0.0, min(1.0, 1.0 - (std_dev / 15.0)))
 
    # ── Metric 2: Type-token ratio ──
    words = re.findall(r"\b[a-zA-Z]+\b", text.lower())
    if not words:
        ttr_score = 0.5
    else:
        ttr = len(set(words)) / len(words)
        # TTR < 0.4 → AI-like; TTR > 0.8 → human-like
        # Map [0.4, 0.8] → [1.0, 0.0]
        ttr_score = max(0.0, min(1.0, 1.0 - (ttr - 0.4) / 0.4))
 
    # ── Metric 3: Expressive punctuation density ──
    expressive_punct = len(re.findall(r"[—–…!?;()\[\]]", text))
    punct_density = expressive_punct / max(1, len(words))
    # > 0.08 → human-like; < 0.01 → AI-like
    # Map [0, 0.08] → [1.0, 0.0]
    punct_score = max(0.0, min(1.0, 1.0 - (punct_density / 0.08)))
 
    return round(0.4 * variance_score + 0.4 * ttr_score + 0.2 * punct_score, 4)
 
 
# ── Confidence Scoring ────────────────────────────────────────────────────────
 
def compute_confidence(llm_score: float, stylometric_score: float) -> dict:
    """
    Combines both signals into a final confidence score and attribution verdict.
 
    Weighting: LLM 60%, stylometric 40%
    Thresholds (asymmetric — favours false-negative over false-positive):
      >= 0.70  → likely_ai
      0.40–0.69 → uncertain
      < 0.40   → likely_human
    """
    confidence = round(0.6 * llm_score + 0.4 * stylometric_score, 4)
 
    if confidence >= 0.70:
        attribution = "likely_ai"
    elif confidence >= 0.40:
        attribution = "uncertain"
    else:
        attribution = "likely_human"
 
    return {"confidence": confidence, "attribution": attribution}


def generate_label(attribution: str, confidence: float) -> str:
    """
    Maps verdict + confidence to the full user-facing transparency label.
 
    Variants:
      likely_ai    — cautions without accusing; surfaces appeal path
      uncertain    — honest about inability to determine; surfaces appeal path
      likely_human — affirming but not overclaiming
    """
    pct = round(confidence * 100)
    human_pct = round((1 - confidence) * 100)
 
    if attribution == "likely_ai":
        return (
            f"Likely AI-generated\n"
            f"Our analysis found strong indicators that this content may have been created "
            f"with AI assistance. Confidence: {pct}%. The author can contest this "
            f"classification if they believe it's incorrect."
        )
    elif attribution == "uncertain":
        return (
            f"Authorship uncertain\n"
            f"Our tools couldn't confidently determine whether this content was written by "
            f"a person or with AI assistance. Confidence in AI authorship: {pct}%. The "
            f"author can provide more context if they'd like."
        )
    else:
        return (
            f"Likely human-written\n"
            f"Our analysis found no significant indicators of AI generation in this content. "
            f"Confidence in human authorship: {human_pct}%."
        )




@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;50 per day")
def submit():
    data=request.get_json(silent=True)
    if not data:
        return jsonify({"error": "Invalid JSON data"}), 400
    text=data.get("text", "").strip()
    creator_id=data.get("creator_id", "").strip()
    if not text:
        return jsonify({"error": "Missing 'text' field"}), 400
    if not creator_id:
        return jsonify({"error": "Missing 'creator_id' field"}), 400
    if len(text) < 10:
        return jsonify({"error": "Text is too short to analyze, must be at least 10 characters"}), 400


    llm_result = llm_classify(text)
    stylo_score= stylometric_classify(text)
    scoring = compute_confidence(llm_result["score"], stylo_score)
    label = generate_label(scoring["attribution"], scoring["confidence"])
    content_id = str(uuid.uuid4())

    log_event({
        "content_id": content_id,
        "creator_id": creator_id,
        "attribution": scoring["attribution"],
        "confidence": scoring["confidence"],
        "status": "classified",
        "llm_score": llm_result["score"],
        "llm_rationale": llm_result["rationale"],
        "stylometric_score": stylo_score,
        "text_excerpt": text[:200]
    })
    return jsonify({
        "content_id": content_id,
        "attribution": scoring["attribution"],
        "confidence": scoring["confidence"],
        "label": label,
        "llm_score": llm_result["score"],
        "llm_rationale": llm_result["rationale"],
        "stylometric_score": stylo_score,
        "text_excerpt": text[:200]
    }), 200
 
@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json(silent=True)
    if not data:
        return jsonify({"error": "Invalid JSON data"}), 400
 
    content_id = data.get("content_id", "").strip()
    reasoning = data.get("creator_reasoning", "").strip()
 
    if not content_id:
        return jsonify({"error": "Missing 'content_id' field"}), 400
    if not reasoning or len(reasoning) < 10:
        return jsonify({"error": "Missing or too-short 'creator_reasoning' field (minimum 10 characters)"}), 400
 
    record = get_record(content_id)
    if not record:
        return jsonify({"error": f"No submission found with content_id: {content_id}"}), 404
 
    if record["status"] == "under_review":
        return jsonify({
            "content_id": content_id,
            "status":     "under_review",
            "message":    "This submission is already under review. A human reviewer will assess it.",
        }), 200
 
    appeal_timestamp = datetime.now(timezone.utc).isoformat()
    update_appeal(content_id, reasoning, appeal_timestamp)
 
    return jsonify({
        "content_id":         content_id,
        "status":             "under_review",
        "appeal_timestamp":   appeal_timestamp,
        "original_attribution": record["attribution"],
        "original_confidence":  record["confidence"],
        "message": (
            "Your appeal has been received and logged. A human reviewer will assess "
            "your submission and its original classification. This decision will be "
            "made by a person, not an automated re-classification."
        ),
    }), 200




@app.route("/log", methods=["GET"])
def view_log():
    return jsonify({"entries": read_log()}), 200

@app.route("/appeals", methods=["GET"])
def view_appeals():
    """Returns all submissions currently under review — the human reviewer queue."""
    with sqlite3.connect(DB_PATH) as conn:
        conn.row_factory = sqlite3.Row
        rows = conn.execute(
            "SELECT * FROM audit_log WHERE status = 'under_review' "
            "ORDER BY appeal_timestamp DESC"
        ).fetchall()
    return jsonify({"count": len(rows), "appeals": [dict(r) for r in rows]}), 200
 
 
@app.errorhandler(429)
def rate_limit_exceeded(e):
    return jsonify({
        "error":   "Rate limit exceeded",
        "message": "Too many submissions. Please wait before trying again.",
    }), 429



#this has to be the last thing
if __name__ == '__main__':
    app.run(port=5000, debug=True)
