from flask import Flask, request, jsonify
import uuid
from groq import Groq
from dotenv import load_dotenv
import os
import re
import json
import sqlite3
from datetime import datetime, timezone

load_dotenv()

app = Flask(__name__)
@app.route('/')
def home():
    return "Provenance Guard is running!"

DB_PATH = "audit_log.db"
def init_db():
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS audit_log (
                content_id  TEXT,
                creator_id  TEXT,
                timestamp   TEXT,
                attribution TEXT,
                confidence  REAL,
                status      TEXT,
                llm_score     REAL,
                llm_rationale TEXT,
                text_excerpt  TEXT

            )
        """)
init_db()
def log_event(entry):
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute(
            "INSERT INTO audit_log VALUES (:content_id, :creator_id, :timestamp, "
            ":attribution, :confidence, :status, :llm_score, :llm_rationale, :text_excerpt)",
            {**entry, "timestamp": datetime.now(timezone.utc).isoformat()},
        )




def read_log(limit=20):
    with sqlite3.connect(DB_PATH) as conn:
        conn.row_factory = sqlite3.Row
        rows = conn.execute(
            "SELECT * FROM audit_log ORDER BY timestamp DESC LIMIT ?", (limit,)
        ).fetchall()
    return [dict(row) for row in rows]


#groq classifier
def llm_classify(text: str) -> dict:
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        return {"score": 0.5, "rationale": "API key not found in environment variables."}
    client = Groq(api_key=api_key)
    prompt = f"""Your purpose is to distinguish between human-written and AI-generated text. Analyze the following text and assess the probability that it was generated by an AI model as opposed to it being written by a human. 
    Consider the following factors in your assessment:
    - Uniformity of tone and sentence structure
    - Presence or absence of genuine personal voice, idiosyncrasies, or lived experience
    - Hedging language patterns typical of LLMs ("it is important to note", "it is worth mentioning", "furthermore")
    - Vocabulary diversity and naturalness
    - Emotional authenticity vs. emotional flatness
    - Whether the writing feels genuinely spontaneous or constructed
    Respond ONLY with a JSON object in this exact format (no other text):
    {{"score": <float between 0.0 and 1.0>, "rationale": "<one to two sentences explaining your reasoning>"}}
    where score = 0.0 means definitely human-written, and score = 1.0 means definitely AI-generated.
    Text to analyze: {text}
"""
    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=200,
            temperature=0.1,
        )
        raw = response.choices[0].message.content.strip()
        raw = re.sub(r"```(?:json)?", "", raw).strip().rstrip("```").strip()
        result = json.loads(raw)
        score = float(result.get("score", 0.5))
        score = max(0.0, min(1.0, score))
        return {"score": score, "rationale": result.get("rationale", "")}
    except Exception as e:
        return {"score": 0.5, "rationale": f"Error during classification: {str(e)}"}

def placeholder_confidence(llm_score: float) -> dict:
    if llm_score >= 0.72:
        attribution = "likely_ai"
    elif llm_score >= 0.40:
        attribution = "uncertain"
    else:
        attribution = "likely_human"
    return {"confidence": llm_score, "attribution": attribution}
def placeholder_label(attribution: str, confidence: float) -> str:
    pct = round(confidence * 100)
    return {
        "likely_ai":    f"Likely AI-generated (confidence: {pct}%)",
        "uncertain":    f"Authorship uncertain (confidence: {pct}%)",
        "likely_human": f"Likely human-written (confidence: {pct}%)",
    }[attribution]




@app.route("/submit", methods=["POST"])
def submit():
    data=request.get_json(silent=True)
    if not data:
        return jsonify({"error": "Invalid JSON data"}), 400
    text=data.get("text", "").strip()
    creator_id=data.get("creator_id", "").strip()
    if not text:
        return jsonify({"error": "Missing 'text' field"}), 400
    if not creator_id:
        return jsonify({"error": "Missing 'creator_id' field"}), 400
    if len(text) < 10:
        return jsonify({"error": "Text is too short to analyze, must be at least 10 characters"}), 400


    llm_result = llm_classify(text)
    scoring = placeholder_confidence(llm_result["score"])
    label = placeholder_label(scoring["attribution"], scoring["confidence"])
    content_id = str(uuid.uuid4())

    log_event({
        "content_id": content_id,
        "creator_id": creator_id,
        "attribution": scoring["attribution"],
        "confidence": scoring["confidence"],
        "status": "classified",
        "llm_score": llm_result["score"],
        "llm_rationale": llm_result["rationale"],
        "text_excerpt": text[:200]
    })
    return jsonify({
        "content_id": content_id,
        "attribution": scoring["attribution"],
        "confidence": scoring["confidence"],
        "label": label,
        "llm_score": llm_result["score"],
        "llm_rationale": llm_result["rationale"],
        "text_excerpt": text[:200]
    }), 200
 
@app.route("/log", methods=["GET"])
def view_log():
    return jsonify({"entries": read_log()}), 200

#this has to be the last thing
if __name__ == '__main__':
    app.run(port=5000, debug=True)
